[project]
name = "commercecontentgenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.45.2",
    "bs4>=0.0.2",
    "markdown>=3.7",
    "streamlit>=1.42.0",
    "watchdog>=6.0.0",
]
