country_languages = {
    "United States": ["English", "Spanish", "Arabic", "Hindi", "Chinese", "French", "Italian", "German"],
    "United Kingdom": ["English", "Arabic", "Hindi", "Chinese", "French", "Italian", "German"],
    "Canada": ["English", "French", "Arabic", "Hindi", "Chinese", "Italian", "German"],
    "Australia": ["English", "Mandarin", "Hindi", "Chinese", "French", "Italian", "German"],
    "Germany": ["German"],
    "France": ["French"],
    "Spain": ["Spanish"],
    "Italy": ["Italian"],
    "Japan": ["Japanese"],
    "Brazil": ["Portuguese"],
    "Mexico": ["Spanish"],
    "Argentina": ["Spanish"],
    "South Africa": ["English", "Afrikaans", "Zulu", "Xhosa"],
    "Russia": ["Russian"],
    "India": ["Hindi", "English"],
    "China": ["Mandarin"],
    "South Korea": ["Korean"],
    "Indonesia": ["Indonesian"],
    "Turkey": ["Turkish"],
    "Saudi Arabia": ["Arabic"],
    "United Arab Emirates": ["Arabic", "English"],
    "Israel": ["Hebrew", "Arabic", "English"],
    "Sweden": ["Swedish"],
    "Norway": ["Norwegian"],
    "Denmark": ["Danish"],
    "Finland": ["Finnish"],
    "Netherlands": ["Dutch"],
    "Belgium": ["Dutch", "French"],
    "Switzerland": ["German", "French", "Italian"],
    "Austria": ["German"],
    "Poland": ["Polish"],
    "Ukraine": ["Ukrainian"],
    "Romania": ["Romanian"],
    "Greece": ["Greek"],
    "Czech Republic": ["Czech"],
    "Portugal": ["Portuguese"],
    "Ireland": ["English", "Irish"],
    "New Zealand": ["English"],
    "Singapore": ["English", "Mandarin", "Malay", "Tamil"],
    "Malaysia": ["Malay", "English"],
    "Philippines": ["Filipino", "English"],
    "Thailand": ["Thai"],
    "Vietnam": ["Vietnamese"],
    "Egypt": ["Arabic"],
    "Nigeria": ["English"],
    "Kenya": ["English", "Swahili"],
    "Morocco": ["Arabic"],
    "Algeria": ["Arabic"],
    "Tunisia": ["Arabic"],
    "Iran": ["Persian"],
    "Pakistan": ["Urdu", "English"],
    "Bangladesh": ["Bengali"],
    "Sri Lanka": ["Sinhala", "Tamil"],
    "Nepal": ["Nepali"],
    "Afghanistan": ["Dari", "Pashto"],
    "Kazakhstan": ["Kazakh", "Russian"],
    "Uzbekistan": ["Uzbek"],
    "Turkmenistan": ["Turkmen"],
    "Kyrgyzstan": ["Kyrgyz", "Russian"],
    "Tajikistan": ["Tajik"],
    "Mongolia": ["Mongolian"],
    "North Korea": ["Korean"],
    "Taiwan": ["Mandarin"],
    "Hong Kong": ["Cantonese", "English"],
    "Macau": ["Cantonese", "Portuguese"],
    "Cambodia": ["Khmer"],
    "Laos": ["Lao"],
    "Myanmar": ["Burmese"],
    "Bhutan": ["Dzongkha"],
    "Maldives": ["Dhivehi"],
    "Brunei": ["Malay"],
    "East Timor": ["Tetum", "Portuguese"],
    "Fiji": ["English", "Fijian", "Hindi"],
        "Papua New Guinea": ["English", "Tok Pisin", "Hiri Motu"],
    "Solomon Islands": ["English"],
    "Vanuatu": ["Bislama", "English", "French"],
    "Samoa": ["Samoan", "English"],
    "Tonga": ["Tongan", "English"],
    "Kiribati": ["English", "Gilbertese"],
    "Micronesia": ["English"],
    "Marshall Islands": ["Marshallese", "English"],
    "Palau": ["Palauan", "English"],
    "Nauru": ["Nauruan", "English"],
    "Tuvalu": ["Tuvaluan", "English"],
    "Cuba": ["Spanish"],
    "Haiti": ["French", "Haitian Creole"],
    "Dominican Republic": ["Spanish"],
    "Jamaica": ["English"],
    "Trinidad and Tobago": ["English"],
    "Bahamas": ["English"],
    "Barbados": ["English"],
    "Saint Lucia": ["English"],
    "Saint Vincent and the Grenadines": ["English"],
    "Grenada": ["English"],
    "Antigua and Barbuda": ["English"],
    "Dominica": ["English"],
    "Saint Kitts and Nevis": ["English"],
    "Belize": ["English"],
    "Guatemala": ["Spanish"],
    "El Salvador": ["Spanish"],
    "Honduras": ["Spanish"],
    "Nicaragua": ["Spanish"],
    "Costa Rica": ["Spanish"],
    "Panama": ["Spanish"],
    "Colombia": ["Spanish"],
    "Venezuela": ["Spanish"],
    "Ecuador": ["Spanish"],
    "Peru": ["Spanish"],
    "Bolivia": ["Spanish"],
    "Paraguay": ["Spanish", "Guarani"],
    "Uruguay": ["Spanish"],
    "Chile": ["Spanish"],
    "Guyana": ["English"],
    "Suriname": ["Dutch"],
    "French Guiana": ["French"],
    "Iceland": ["Icelandic"],
    "Andorra": ["Catalan"],
    "Monaco": ["French"],
    "Liechtenstein": ["German"],
    "San Marino": ["Italian"],
    "Vatican City": ["Italian"],
    "Malta": ["Maltese", "English"],
    "Cyprus": ["Greek", "Turkish"],
    "Luxembourg": ["Luxembourgish", "French", "German"],
    "Bosnia and Herzegovina": ["Bosnian", "Croatian", "Serbian"],
    "Serbia": ["Serbian"],
    "Montenegro": ["Montenegrin"],
    "North Macedonia": ["Macedonian"],
    "Albania": ["Albanian"],
    "Kosovo": ["Albanian", "Serbian"],
    "Moldova": ["Romanian"],
    "Belarus": ["Belarusian", "Russian"],
    "Georgia": ["Georgian"],
    "Armenia": ["Armenian"],
    "Azerbaijan": ["Azerbaijani"],
    "Syria": ["Arabic"],
    "Lebanon": ["Arabic", "French"],
    "Jordan": ["Arabic"],
    "Iraq": ["Arabic", "Kurdish"],
    "Kuwait": ["Arabic"],
    "Bahrain": ["Arabic"],
    "Qatar": ["Arabic"],
    "Oman": ["Arabic"],
    "Yemen": ["Arabic"],
    "Libya": ["Arabic"],
    "Sudan": ["Arabic", "English"],
    "South Sudan": ["English"],
    "Eritrea": ["Tigrinya", "Arabic", "English"],
    "Ethiopia": ["Amharic"],
    "Djibouti": ["French", "Arabic"],
    "Somalia": ["Somali", "Arabic"],
    "Uganda": ["English", "Swahili"],
    "Rwanda": ["Kinyarwanda", "English", "French"],
    "Burundi": ["Kirundi", "French"],
    "Tanzania": ["Swahili", "English"],
    "Zambia": ["English"],
    "Malawi": ["English"],
    "Mozambique": ["Portuguese"],
    "Madagascar": ["Malagasy", "French"],
        "Mauritius": ["English", "French"],
    "Seychelles": ["Seychellois Creole", "English", "French"],
    "Comoros": ["Comorian", "Arabic", "French"],
    "Botswana": ["English", "Tswana"],
    "Namibia": ["English"],
    "Zimbabwe": ["English", "Shona", "Ndebele"],
    "Lesotho": ["English", "Sesotho"],
    "Eswatini": ["English", "Swati"],
    "Angola": ["Portuguese"],
    "Democratic Republic of the Congo": ["French"],
    "Republic of the Congo": ["French"],
    "Gabon": ["French"],
    "Equatorial Guinea": ["Spanish", "French"],
    "Cameroon": ["English", "French"],
    "Central African Republic": ["French", "Sango"],
    "Chad": ["French", "Arabic"],
    "Benin": ["French"],
    "Togo": ["French"],
    "Ghana": ["English"],
    "Ivory Coast": ["French"],
    "Liberia": ["English"],
    "Sierra Leone": ["English"],
    "Guinea": ["French"],
    "Guinea-Bissau": ["Portuguese"],
    "Senegal": ["French"],
    "Gambia": ["English"],
    "Cape Verde": ["Portuguese"],
    "Mauritania": ["Arabic"],
    "Mali": ["French"],
    "Burkina Faso": ["French"],
    "Niger": ["French"],
    "Sao Tome and Principe": ["Portuguese"],
    "Timor-Leste": ["Tetum", "Portuguese"],
    "Papua New Guinea": ["English", "Tok Pisin", "Hiri Motu"],
    "Solomon Islands": ["English"],
    "Vanuatu": ["Bislama", "English", "French"],
    "Samoa": ["Samoan", "English"],
    "Tonga": ["Tongan", "English"],
    "Kiribati": ["English", "Gilbertese"],
    "Micronesia": ["English"],
    "Marshall Islands": ["Marshallese", "English"],
    "Palau": ["Palauan", "English"],
    "Nauru": ["Nauruan", "English"],
    "Tuvalu": ["Tuvaluan", "English"]
}